# Generated by Django 2.1.4 on 2018-12-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_auto_20181216_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('veh_type', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('vehicle_age', models.CharField(max_length=20)),
            ],
        ),
    ]
