# Generated by Django 2.1.4 on 2018-12-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='area',
        ),
        migrations.AddField(
            model_name='person',
            name='date_from',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='date_to',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
